pipeline:
  test_go:
    image: registry.quan.io/dan/golang-testing
    commands:
      - go test ./go/...
      - golint -set_exit_status go/...
  test_elixir:
    image: elixir
    commands:
      - for file in elixir/**/*_test.exs; do elixir "$file"; done
  test_rust:
    image: rust
    commands:
      - for dir in rust/*; do (cd "$dir" && cargo test); done

