name: Elixir CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: find . -name *_test.exs -print0 | xargs -n 1 -0 elixir
