name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Install Lint
      run: go get -u golang.org/x/lint/golint      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: go test ./go/...
    - name: Lint
      run: $(go list -f {{.Target}} golang.org/x/lint/golint) --set_exit_status go/...
